### ISSUE TITLE
Add PostgresConnectionConfigProvider

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/dropwizard-config-providers#33]
Provides config values for the following properties:

* `String url`
* `String user`
* `String password`

**Comment by chrisrohr** [comment]
@sleberknight I've started implementing this (as a RelationalDbConnectionConfigProvider), however, after seeing it, I'm not sure there is anything different between this and the `DropwizardDataSourceConfigProvider`.  They both have url, user and password.  Thoughts?

**Comment by sleberknight** [comment]
If there is nothing specific to Postgres, could just make it a JdbcConnectionConfigProvider.

**Comment by chrisrohr** [comment]
Ok, since this has the same fields as the `DropwizardDataSourceConfigProvider` I am going to close this one.  We can revisit if we need Postgres specific config values
